import { FileDown } from "lucide-react";

export default function PDFReportButton({ result }) {
  if (!result) return null;

  function downloadReport() {
    const report = `
=============================
      TruthLens AI Report
=============================

Prediction : ${result.prediction}
Confidence : ${result.confidence}%
AI Model   : ${result.model}

-----------------------------
FORENSIC ANALYSIS
-----------------------------

Resolution : ${result.forensics.image_quality.resolution}
Sharpness  : ${result.forensics.image_quality.blur}
Brightness : ${result.forensics.image_quality.brightness}
File Size  : ${result.forensics.image_quality.file_size_mb} MB

Faces Detected : ${result.forensics.face_analysis.faces_detected}

Camera : ${result.forensics.metadata.camera}

Generated by TruthLens AI
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "TruthLens_Report.txt";

    a.click();

    URL.revokeObjectURL(url);
  }

  return (
    <button
      onClick={downloadReport}
      className="flex items-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 font-semibold text-white transition hover:bg-emerald-500"
    >
      <FileDown size={20} />
      Download Report
    </button>
  );
}